// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logo': string;
  'logoContainer': string;
  'menu': string;
  'menuButton': string;
  'menuButtonContainer': string;
  'menuToggle': string;
  'topNav': string;
}
export const cssExports: CssExports;
export default cssExports;
