// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'footer': string;
  'header': string;
  'sidebar': string;
}
export const cssExports: CssExports;
export default cssExports;
